spring.application.name=Sonata
server.port=8081
# test or dev
# spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.web.error.include-stacktrace=never
#spring.web.error.include-message=never
#spring.web.error.include-binding-errors=never
