spring.application.name=Sonata
server.port=8081
# test or dev
spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
