spring.application.name=Sonata
server.port=8081

# test or dev
spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never

# JWT secret (replace with a secure, random value in production)
application.jwt.secret=change_this_secret_to_a_long_random_value
